# Generated by Django 3.2.9 on 2021-11-21 11:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
