# Generated by Django 3.2.9 on 2021-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20211126_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respond',
            name='update',
        ),
        migrations.AddField(
            model_name='respond',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
